title: Jayvardhan Rathi # your name (or website title) here
logo: "/images/filename.png"
description: >
  Pre Final Undergraduate in Compter Science & Engineering, SRM IST.
  <br>
  Primarily interested in Backend Development & Distributed Systems. 
  <br>
  <a href="https://ComputerScientist-01.io/pdf/Jayvardhan_Overleaf.pdf">View My Resume</a>
  <br>
  <a href="https://ComputerScientist-01.io/pdf/Jayvardhan.pdf">View My College Resume</a>
  <br>
  <a href="https://www.linkedin.com/in/rathi406">View My LinkedIn Profile</a> 
  <br>
  <a href="https://github.com/ComputerScientist-01">View My Github Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
